source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LeoDanmakuKit_Example', :exclusive => true do
  pod "LeoDanmakuKit", :path => "../"
end

target 'LeoDanmakuKit_Tests', :exclusive => true do
  pod "LeoDanmakuKit", :path => "../"

  
end
